### ISSUE TITLE
Validate that a reference callable exists

### ISSUE THREAD

**Issue by fnikolai** [CARV-ICS-FORTH/frisbee#354]
This is a bit tricky and cannot be done at the admission level, because it requires access to the referenced template.

Instead, it must be done at the scenario level, when all the templates are loaded.

**Comment by fnikolai** [comment]
This remains tricky because Call may refer to services that are not yet created.
Therefore, we cannot retrieve its spec. It may need some "guessing" to find the type of the service. For example, "masters-1" would be from cluster, whereas "master" would be from service.

```yaml
    - action: Call
      name: wait-for-3x-replication
      depends: { success: [ import-workload ] }
      call:
        callable: wait-for-3x-replication
        services: [ masters-1 ]
```

But this can cause configuration is a service is explicitly called "masters-1".
