### ISSUE TITLE
Cluster resource does not work properly

### ISSUE THREAD

**Issue by fnikolai** [CARV-ICS-FORTH/frisbee#377]
the resource defition on cluster 
```
      cluster:
        templateRef: fedbed.client
        resources:
          total: { cpu: 60, mem: 60Gi } # Change values here
          distribution: { name: uniform }
```
sets the CPU but not the memory
